#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one-time GCP setup for the Cloud Run deploy (spec §9.7).
#
# Source of truth: docs/DEPLOYING.md and
# .github/workflows/deploy-service.yml. Nothing here is a credential the
# workflow sees: GitHub authenticates as this repository via Workload Identity
# Federation, and the five real secrets live in GCP Secret Manager.
#
# Safe to re-run. Values already in .env come back as defaults, secrets get a
# new version rather than a duplicate, and "already exists" is treated as done.
# ──────────────────────────────────────────────────────────────────────────

# The script lives in scripts/, but .env, ./gradlew and gh's repo detection all
# resolve from the repo root. Go there before anything reads or writes.
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

TOTAL_STAGES=11

REPO="varun1221/forecastapp"
POOL="github"
PROVIDER="forecastapp"
AR_REPO="forecast"
SECRET_NAMES=(
  forecast-db-url
  forecast-db-password
  forecast-tomtom-key
  forecast-origin-secret
  forecast-ip-hash-secret
)

# run_step "what it does" cmd... — runs a command, treating the "already
# exists" of a re-run as success and letting the human decide about anything
# else. Keeps the wizard idempotent without pretending failures didn't happen.
run_step() {
  local desc="$1"; shift
  local out status=0
  out=$("$@" 2>&1) || status=$?
  if (( status == 0 )); then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$desc"
  elif printf '%s' "$out" | grep -qiE 'already exists|ALREADY_EXISTS'; then
    printf '  %s✓%s %s %s(already there)%s\n' "$GREEN" "$RESET" "$desc" "$DIM" "$RESET"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$desc"
    printf '%s\n' "$out" | sed 's/^/      /'
    SKIPPED+=("$desc")
    confirm "Continue anyway?" || exit 1
  fi
}

# put_secret NAME VALUE — create the secret, or add a version if it's there.
put_secret() {
  local name="$1" value="$2"
  if gcloud secrets describe "$name" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    printf '%s' "$value" \
      | gcloud secrets versions add "$name" --data-file=- --project "$GCP_PROJECT_ID" >/dev/null
    printf '  %s✓%s %s %s(new version)%s\n' "$GREEN" "$RESET" "$name" "$DIM" "$RESET"
  else
    printf '%s' "$value" \
      | gcloud secrets create "$name" --data-file=- --replication-policy=automatic \
          --project "$GCP_PROJECT_ID" >/dev/null
    printf '  %s✓%s %s %s(created)%s\n' "$GREEN" "$RESET" "$name" "$DIM" "$RESET"
  fi
}

banner "Cloud Run setup for forecast-service"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud CLI"
say "Everything after this stage is gcloud driving your account, so the CLI"
say "has to exist and be logged in as you."
if command -v gcloud >/dev/null 2>&1; then
  note "gcloud found: $(command -v gcloud)"
else
  warn "gcloud isn't installed."
  if command -v brew >/dev/null 2>&1 && confirm "Install it now with Homebrew? (a few minutes)"; then
    brew install --cask google-cloud-sdk || warn "Homebrew couldn't install it."
    note "If gcloud still isn't on PATH, open a new terminal and re-run this script."
  else
    say "Install it, then re-run this script:"
    note "  brew install --cask google-cloud-sdk"
    open_url "https://cloud.google.com/sdk/docs/install"
    exit 1
  fi
fi
command -v gcloud >/dev/null 2>&1 || { warn "gcloud still not on PATH — open a new terminal and re-run."; exit 1; }
if gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  note "signed in as $(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -n1)"
else
  step "A browser window will open for Google sign-in."
  pause "Press Enter to sign in"
  gcloud auth login
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Project and billing"
say "Cloud Run's free tier is real, but a project still needs a billing account"
say "with a card on file before anything will deploy. That is the one thing"
say "nobody can automate for you."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project (any name). Copy its Project ID — not the display name;"
step "the ID is the lowercase one with digits, e.g. forecast-470112."
ask GCP_PROJECT_ID "Project ID:"
[[ -n "$GCP_PROJECT_ID" ]] || { warn "A project ID is required."; exit 1; }
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

say ""
say "Region: Cloud Run's free tier exists in three regions and nowhere else."
while true; do
  ask GCP_REGION "Region [us-central1, us-east1, us-west1]:"
  [[ -z "$GCP_REGION" ]] && GCP_REGION="us-central1"
  case "$GCP_REGION" in
    us-central1|us-east1|us-west1) break ;;
    *) warn "That region has no Cloud Run free tier. Pick one of the three." ;;
  esac
done
write_env GCP_REGION "$GCP_REGION"

run_step "select project $GCP_PROJECT_ID" gcloud config set project "$GCP_PROJECT_ID"
open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
step "Link a billing account to the project (the \$300 trial credit counts)."
warn "Do NOT create a Cloud SQL instance if the console offers one — the database"
warn "is Neon, which is free. Cloud SQL is the one thing here that would bill you."
pause "Press Enter once billing is linked"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable the APIs"
say "Five services, plus Compute Engine — that last one only so the default"
say "compute service account exists, which is the identity the Cloud Run"
say "revision runs as and the one that reads the secrets."
run_step "enable APIs" gcloud services enable \
  run.googleapis.com \
  artifactregistry.googleapis.com \
  secretmanager.googleapis.com \
  iamcredentials.googleapis.com \
  sts.googleapis.com \
  compute.googleapis.com \
  --project "$GCP_PROJECT_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon Postgres"
say "The service's database. Free, no card, and it autosuspends when idle —"
say "spec §4 picked it for exactly that."
if [[ -n "$(_existing DB_URL || true)" ]]; then
  note "a Neon database is already recorded in .env:"
  note "  $(_existing DB_URL)"
  if ! confirm "Set up a different one?"; then
    DB_URL=$(_existing DB_URL)
    DB_USER=$(_existing DB_USER)
    DB_PASSWORD=$(_existing DB_PASSWORD)
    NEON_DONE=1
  fi
fi

if [[ -z "${NEON_DONE:-}" ]]; then
  open_url "https://console.neon.tech/signup"
  step "Create a project. Name the database 'forecast'."
  step "Pick the Neon region closest to $GCP_REGION so lookups aren't crossing the country."
  step "On the dashboard, open the connection string dropdown and turn"
  step "  'Connection pooling' OFF — Flyway takes an advisory lock at startup and"
  step "  the pooler's transaction mode drops it, which fails the migration."
  step "Copy the direct connection string. It looks like:"
  note "  postgresql://user:password@ep-something.us-west-2.aws.neon.tech/forecast?sslmode=require"
  ask_secret NEON_CONNECTION_STRING "Paste the Neon connection string:"
  if [[ -z "${NEON_CONNECTION_STRING:-}" ]]; then
    warn "Nothing pasted — the deploy can't come up without a database."
    exit 1
  fi
  _raw="${NEON_CONNECTION_STRING#postgresql://}"
  _raw="${_raw#postgres://}"
  _creds="${_raw%%@*}"
  _rest="${_raw#*@}"
  DB_USER="${_creds%%:*}"
  DB_PASSWORD="${_creds#*:}"
  _hostdb="${_rest%%\?*}"
  DB_URL="jdbc:postgresql://${_hostdb}?sslmode=require"
  if [[ "$DB_URL" != *"neon.tech"* ]] || [[ -z "$DB_USER" ]] || [[ "$DB_USER" == "$DB_PASSWORD" ]]; then
    warn "That didn't parse as a Neon connection string. Expected the postgresql:// form."
    exit 1
  fi
  say ""
  note "user: $DB_USER"
  note "url:  $DB_URL"
  note "password: (hidden, captured)"
  confirm "Does that look right?" || { warn "Re-run and paste the direct connection string."; exit 1; }
  write_env DB_USER "$DB_USER"
  write_env DB_URL "$DB_URL"
  write_env DB_PASSWORD "$DB_PASSWORD"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Artifact Registry"
say "Where deploy-service.yml pushes the image before Cloud Run pulls it."
run_step "create repository '$AR_REPO' in $GCP_REGION" \
  gcloud artifacts repositories create "$AR_REPO" \
    --repository-format=docker --location="$GCP_REGION" --project "$GCP_PROJECT_ID"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Secret Manager"
say "Five secrets. The workflow names them but never sees them — Cloud Run"
say "reads them at deploy time, so nothing sensitive passes through Actions."
say ""
say "The origin secret and the IP hash key are generated here and exist nowhere"
say "else. On a re-run the values in .env are reused rather than rotated: a new"
say "origin secret would silently break the Cloudflare rule that sends it."
ORIGIN_SECRET=$(_existing ORIGIN_SECRET || true)
if [[ -z "$ORIGIN_SECRET" ]]; then
  ORIGIN_SECRET=$(openssl rand -hex 32)
  note "generated a new origin secret"
else
  note "reusing the origin secret already in .env"
fi
write_env ORIGIN_SECRET "$ORIGIN_SECRET"

IP_HASH_SECRET=$(_existing IP_HASH_SECRET || true)
if [[ -z "$IP_HASH_SECRET" ]]; then
  IP_HASH_SECRET=$(openssl rand -hex 32)
  note "generated a new IP hash key"
else
  note "reusing the IP hash key already in .env"
fi
warn "Rotating the IP hash key orphans every hash already in ip_daily_usage,"
warn "which resets today's per-IP counters. Harmless now, worth knowing later."
write_env IP_HASH_SECRET "$IP_HASH_SECRET"

say ""
ask_secret TOMTOM_API_KEY "TomTom API key:"
[[ -n "${TOMTOM_API_KEY:-}" ]] || { warn "The lookup endpoint needs it."; exit 1; }
write_env TOMTOM_API_KEY "$TOMTOM_API_KEY"

say ""
put_secret forecast-db-url         "$DB_URL"
put_secret forecast-db-password    "$DB_PASSWORD"
put_secret forecast-tomtom-key     "$TOMTOM_API_KEY"
put_secret forecast-origin-secret  "$ORIGIN_SECRET"
put_secret forecast-ip-hash-secret "$IP_HASH_SECRET"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Service accounts"
say "Two identities, and which role goes on which is the detail worth getting"
say "right the first time:"
say ""
say "  deploy  — the one GitHub impersonates. Builds, pushes, deploys."
say "  runtime — the one the revision runs as. Reads the five secrets."
say ""
say "Granting secretAccessor to the deploy account instead fails at deploy time"
say "with an error that names the wrong identity, which is a bad hour."
PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
GCP_DEPLOY_SA="deploy@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
RUNTIME_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
note "deploy:  $GCP_DEPLOY_SA"
note "runtime: $RUNTIME_SA"
say ""
run_step "create the deploy service account" \
  gcloud iam service-accounts create deploy \
    --display-name="GitHub Actions deploy" --project "$GCP_PROJECT_ID"
run_step "grant run.admin to deploy" \
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:$GCP_DEPLOY_SA" --role="roles/run.admin" --condition=None
run_step "grant artifactregistry.writer to deploy" \
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:$GCP_DEPLOY_SA" --role="roles/artifactregistry.writer" --condition=None
run_step "let deploy act as the runtime account" \
  gcloud iam service-accounts add-iam-policy-binding "$RUNTIME_SA" \
    --member="serviceAccount:$GCP_DEPLOY_SA" --role="roles/iam.serviceAccountUser" \
    --project "$GCP_PROJECT_ID"
for s in "${SECRET_NAMES[@]}"; do
  run_step "let runtime read $s" \
    gcloud secrets add-iam-policy-binding "$s" \
      --member="serviceAccount:$RUNTIME_SA" --role="roles/secretmanager.secretAccessor" \
      --project "$GCP_PROJECT_ID"
done
write_env GCP_DEPLOY_SA "$GCP_DEPLOY_SA"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Workload Identity Federation"
say "This is what lets GitHub deploy without a long-lived key. The provider is"
say "restricted to $REPO — that restriction is the entire point,"
say "since without it any repository on GitHub could mint the same token."
run_step "create the identity pool" \
  gcloud iam workload-identity-pools create "$POOL" \
    --location=global --display-name="GitHub Actions" --project "$GCP_PROJECT_ID"
run_step "create the OIDC provider, restricted to $REPO" \
  gcloud iam workload-identity-pools providers create-oidc "$PROVIDER" \
    --location=global --workload-identity-pool="$POOL" \
    --issuer-uri="https://token.actions.githubusercontent.com" \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
    --attribute-condition="assertion.repository=='${REPO}'" \
    --project "$GCP_PROJECT_ID"
POOL_NAME=$(gcloud iam workload-identity-pools describe "$POOL" \
  --location=global --project "$GCP_PROJECT_ID" --format='value(name)')
run_step "let $REPO impersonate the deploy account" \
  gcloud iam service-accounts add-iam-policy-binding "$GCP_DEPLOY_SA" \
    --role="roles/iam.workloadIdentityUser" \
    --member="principalSet://iam.googleapis.com/${POOL_NAME}/attribute.repository/${REPO}" \
    --project "$GCP_PROJECT_ID"
GCP_WIF_PROVIDER=$(gcloud iam workload-identity-pools providers describe "$PROVIDER" \
  --location=global --workload-identity-pool="$POOL" \
  --project "$GCP_PROJECT_ID" --format='value(name)')
note "provider: $GCP_WIF_PROVIDER"
write_env GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub repository variables"
say "Five variables, none of them credentials. The workflow sits behind"
say "  if: vars.GCP_PROJECT_ID != ''"
say "so setting these is the ignition — nothing to uncomment."
set_var GCP_PROJECT_ID   "$GCP_PROJECT_ID"
set_var GCP_REGION       "$GCP_REGION"
set_var GCP_WIF_PROVIDER "$GCP_WIF_PROVIDER"
set_var GCP_DEPLOY_SA    "$GCP_DEPLOY_SA"
set_var DB_USER          "$DB_USER"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Seed the database"
say "A one-off import from this laptop, not part of the image: the committed"
say "sweeps in data/ go into Neon once, and the deployed service reads them."
say "Flyway creates the schema on first connection, so this is also the honest"
say "test of whether the connection string works."
if confirm "Run the seed import now?"; then
  DB_URL="$DB_URL" DB_USER="$DB_USER" DB_PASSWORD="$DB_PASSWORD" \
    ./gradlew :service:bootRun --args='--import-seed' \
    || { warn "Import failed. The values are saved in .env, so fix and re-run:"
         note "  ./gradlew :service:bootRun --args='--import-seed'"
         SKIPPED+=("seed import"); }
else
  SKIPPED+=("seed import — run: ./gradlew :service:bootRun --args='--import-seed'")
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "What happens on the next push"
say "GCP is configured. Pushing anything under service/ to main now builds the"
say "jar image, pushes it, and deploys it. You can also fire it by hand:"
note "  gh workflow run deploy-service.yml"
say ""
say "Its last step asks Cloud Run directly for /api/quota and expects a 403."
say "That passes from the first revision: the origin secret is already in"
say "Secret Manager, so the service refuses any request that skipped Cloudflare."
say "It also means nothing works through the API hostname until step 3 below."
say ""
say "The rest is outside GCP's deploy, in this order. docs/DEPLOYING.md has"
say "the commands and the reasons:"
step "1. Domain mapping: gcloud beta run domain-mappings create for the API"
step "   hostname, after verifying the domain in Google Search Console."
step "2. DNS: CNAME api -> ghs.googlehosted.com, DNS only (grey cloud) until"
step "   Google has issued the certificate (about 50 minutes), then Proxied."
step "3. Cloudflare Transform Rule: on the API hostname, set X-Origin-Secret"
step "   to the origin secret."
note "   The value is in .env as ORIGIN_SECRET."
step "4. Cloudflare rate-limit rule, the \$1 spend cap and the Artifact"
step "   Registry cleanup policy."
step "5. VITE_API_BASE in the Pages environment, in the SAME commit that adds"
step "   the hostname to connect-src in web/public/_headers, or CSP blocks every"
step "   lookup and the panel reports an unreachable service."
say ""
open_url "https://github.com/$REPO/blob/main/docs/DEPLOYING.md#the-service"

finish
